### ISSUE TITLE
Unrelayed txs

### ISSUE THREAD

**Issue by angelorc** [cosmos/relayer#226] opened 2020-05-06 00:44 UTC
## Problem
I have unrelayed txs. When I try to run `rly tx rly <path>` I get
```
$ rly tx rly goz-path -d
Error: no packet data found
no packet data found
```
## Query full-path
```
{
  "chains": {
    "gameofzoneshub-1a": {
      "reachable": true,
      "height": "36344",
      "client": {
        "id": "wollcojoza",
        "height": "96"
      },
      "connection": {
        "id": "jvvvcipjlz",
        "state": "OPEN"
      },
      "channel": {
        "id": "rpuqkxcrtb",
        "port": "transfer",
        "state": "OPEN",
        "order": "ORDERED"
      }
    },
    "baz-chain3": {
      "reachable": true,
      "height": "6856",
      "client": {
        "id": "vsjuqhfheb",
        "height": "30268"
      },
      "connection": {
        "id": "tfthfskhix",
        "state": "OPEN"
      },
      "channel": {
        "id": "pbreehjdip",
        "port": "transfer",
        "state": "OPEN",
        "order": "ORDERED"
      }
    }
  },
  "unrelayed-seq": {
    "src": [
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10"
    ]
  }
}
```

**Comment by jackzampolin** [comment] 2020-05-21 23:56
I've been unable to reproduce this issue and we just cut a new release. I'm going to close this issue as likely solved.

**Closed as completed** 2020-05-21 23:56 UTC
