### ISSUE TITLE
`rly tx channel` cmd bug

### ISSUE THREAD

**Issue by meetrick** [cosmos/relayer#973] opened 2022-09-06 04:27 UTC
# `rly tx channel` cmd bug
- If I try the following command to create a channel, only the 'No cached' log is repeated and the channel is not created.
```
$ rly tx channel pathname
No cached IBC header for client trusted height	{"chain_id":
No cached IBC header for client trusted height	{"chain_id":
Queried latest height	{"chain_name":
Queried latest height	{"chain_name":
Queried latest height	{"chain_name":
Queried latest height	{"chain_name":
```

**Comment by meetrick** [comment] 2022-09-06 04:28
This issue occurs in the same way when 'rly tx link'.
The client and connection ID are created, but no channel is created.

**Comment by jtieri** [comment] 2022-09-13 12:42
Thanks for opening an issue. After trying `rly tx link` on the Osmosis<>Juno testnet I can confirm the channel creation process does appear to be failing. I'm going to dump some logs here.

Chain configs:

```
juno:
        type: cosmos
        value:
            key: default
            chain-id: uni-3
            rpc-addr: https://rpc.uni.junonetwork.io:443
            account-prefix: juno
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01ujunox
            min-gas-amount: 0
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
osmosis:
        type: cosmos
        value:
            key: default
            chain-id: osmo-test-4
            rpc-addr: https://rpc-test.osmosis.zone:443
            account-prefix: osmo
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.00uosmo
            min-gas-amount: 0
            debug: false
            timeout: 60s
            output-format: json
            sign-mode: direct
```

Logs from `rly tx link juno-osmo-test`:

```
~:rly tx link juno-osmo-test -b 75 -t 30s
2022-09-13T12:30:39.335576Z     info    Successful transaction  {"provider_type": "cosmos", "chain_id": "osmo-test-4", "gas_used": 83261, "fees": "", "fee_payer": "osmo177epemfjfz65j8u0dfy79953k8myw8fc648xa9", "height": 6636209, "msg_types": ["/ibc.core.client.v1.MsgCreateClient"], "tx_hash": "26751E7A5E617F34DBC880273C538EE6052103A5597600D44483BACE4DD4407B"}
2022-09-13T12:30:39.336035Z     info    Client Created  {"src_chain_id": "osmo-test-4", "src_client_id": "07-tendermint-2571", "dst_chain_id": "uni-3"}
2022-09-13T12:31:01.332322Z     info    Successful transaction  {"provider_type": "cosmos", "chain_id": "uni-3", "gas_used": 94115, "fees": "960ujunox", "fee_payer": "juno177epemfjfz65j8u0dfy79953k8myw8fcyuhdvt", "height": 1710085, "msg_types": ["/ibc.core.client.v1.MsgCreateClient"], "tx_hash": "62C29A190B40B2BDB2E4645E446D984C4ABD8D109CB1516E9A2575CF33B6FE65"}
2022-09-13T12:31:01.332371Z     info    Client Created  {"src_chain_id": "uni-3", "src_client_id": "07-tendermint-317", "dst_chain_id": "osmo-test-4"}
2022-09-13T12:31:01.332392Z     info    Clients created {"src_client_id": "07-tendermint-317", "src_chain_id": "uni-3", "dst_client_id": "07-tendermint-2571", "dst_chain_id": "osmo-test-4"}
2022-09-13T12:31:01.337357Z     info    Starting event processor for connection handshake       {"src_chain_id": "uni-3", "src_client_id": "07-tendermint-317", "dst_chain_id": "osmo-test-4", "dst_client_id": "07-tendermint-2571"}
2022-09-13T12:31:01.718263Z     info    Chain is not yet in sync        {"chain_name": "osmosis", "chain_id": "osmo-test-4", "latest_queried_block": 6636138, "latest_height": 6636213}
2022-09-13T12:31:02.150029Z     info    Chain is not yet in sync        {"chain_name": "juno", "chain_id": "uni-3", "latest_queried_block": 1710010, "latest_height": 1710085}
2022-09-13T12:31:15.898160Z     info    Connection handshake termination candidate      {"path_name": "juno-osmo-test", "chain_id": "osmo-test-4", "client_id": "07-tendermint-2571", "termination_client_id": "07-tendermint-2571", "observed_client_id": "07-tendermint-2570", "termination_counterparty_client_id": "07-tendermint-317", "observed_counterparty_client_id": "07-tendermint-316"}
2022-09-13T12:31:15.972697Z     info    Chain is not yet in sync        {"chain_name": "osmosis", "chain_id": "osmo-test-4", "latest_queried_block": 6636213, "latest_height": 6636216}
2022-09-13T12:31:16.979480Z     info    Chain is in sync        {"chain_name": "osmosis", "chain_id": "osmo-test-4"}
2022-09-13T12:31:21.621686Z     info    Chain is not yet in sync        {"chain_name": "juno", "chain_id": "uni-3", "latest_queried_block": 1710085, "latest_height": 1710088}
2022-09-13T12:31:22.623999Z     info    Chain is in sync        {"chain_name": "juno", "chain_id": "uni-3"}
2022-09-13T12:31:29.442707Z     info    Successful transaction  {"provider_type": "cosmos", "chain_id": "uni-3", "gas_used": 133267, "fees": "1428ujunox", "fee_payer": "juno177epemfjfz65j8u0dfy79953k8myw8fcyuhdvt", "height": 1710090, "msg_types": ["/ibc.core.client.v1.MsgUpdateClient", "/ibc.core.connection.v1.MsgConnectionOpenInit"], "tx_hash": "FCD2779298326D46091E8C289ABC8ADA82C0289E2DCCA694B920D648051F8C23"}
2022-09-13T12:31:39.616871Z     info    Successful transaction  {"provider_type": "cosmos", "chain_id": "osmo-test-4", "gas_used": 259704, "fees": "", "fee_payer": "osmo177epemfjfz65j8u0dfy79953k8myw8fc648xa9", "height": 6636221, "msg_types": ["/ibc.core.client.v1.MsgUpdateClient", "/ibc.core.connection.v1.MsgConnectionOpenTry"], "tx_hash": "958B3BB6E483FCA72E9F5AC4765C11E49F66D851E75677E04C0ACC9E5F8BC4A3"}
2022-09-13T12:32:02.866794Z     info    Successful transaction  {"provider_type": "cosmos", "chain_id": "uni-3", "gas_used": 234689, "fees": "2646ujunox", "fee_payer": "juno177epemfjfz65j8u0dfy79953k8myw8fcyuhdvt", "height": 1710096, "msg_types": ["/ibc.core.client.v1.MsgUpdateClient", "/ibc.core.connection.v1.MsgConnectionOpenAck"], "tx_hash": "84F5997CEAC13F1599677A75A4D769BF8E615914925283D6406152ACF5EDB5D0"}
2022-09-13T12:32:14.726695Z     info    Successful transaction  {"provider_type": "cosmos", "chain_id": "osmo-test-4", "gas_used": 207393, "fees": "", "fee_payer": "osmo177epemfjfz65j8u0dfy79953k8myw8fc648xa9", "height": 6636228, "msg_types": ["/ibc.core.client.v1.MsgUpdateClient", "/ibc.core.connection.v1.MsgConnectionOpenConfirm"], "tx_hash": "E2C497AFC656BC094B81FECB6398DF705AA123D32392D9CB680DA277A852FB07"}
2022-09-13T12:32:15.256472Z     info    Connection handshake termination candidate      {"path_name": "juno-osmo-test", "chain_id": "osmo-test-4", "client_id": "07-tendermint-2571", "termination_client_id": "07-tendermint-2571", "observed_client_id": "07-tendermint-2571", "termination_counterparty_client_id": "07-tendermint-317", "observed_counterparty_client_id": "07-tendermint-317"}
2022-09-13T12:32:15.256511Z     info    Found termination condition for connection handshake    {"path_name": "juno-osmo-test", "chain_id": "osmo-test-4", "client_id": "07-tendermint-2571"}
2022-09-13T12:32:15.706251Z     info    Starting event processor for channel handshake  {"src_chain_id": "uni-3", "src_port_id": "transfer", "dst_chain_id": "osmo-test-4", "dst_port_id": "transfer"}
2022-09-13T12:32:16.062528Z     info    Chain is in sync        {"chain_name": "osmosis", "chain_id": "osmo-test-4"}
2022-09-13T12:32:16.330567Z     info    Chain is in sync        {"chain_name": "juno", "chain_id": "uni-3"}
2022-09-13T12:32:31.021524Z     info    Successful transaction  {"provider_type": "cosmos", "chain_id": "uni-3", "gas_used": 178175, "fees": "1967ujunox", "fee_payer": "juno177epemfjfz65j8u0dfy79953k8myw8fcyuhdvt", "height": 1710101, "msg_types": ["/ibc.core.client.v1.MsgUpdateClient", "/ibc.core.channel.v1.MsgChannelOpenInit"], "tx_hash": "6F9168527BFCB825D54444BADBD3971C79434F04FF7F4B6D53E7D327DC8E5731"}
2022-09-13T12:32:39.918879Z     info    Successful transaction  {"provider_type": "cosmos", "chain_id": "osmo-test-4", "gas_used": 260346, "fees": "", "fee_payer": "osmo177epemfjfz65j8u0dfy79953k8myw8fc648xa9", "height": 6636233, "msg_types": ["/ibc.core.client.v1.MsgUpdateClient", "/ibc.core.channel.v1.MsgChannelOpenTry"], "tx_hash": "8C6C9D02863183A77D3746EC52348892B1E79E385675AB206C64F441A4FD1B43"}
2022-09-13T12:33:05.042908Z     info    Successful transaction  {"provider_type": "cosmos", "chain_id": "osmo-test-4", "gas_used": 260686, "fees": "", "fee_payer": "osmo177epemfjfz65j8u0dfy79953k8myw8fc648xa9", "height": 6636238, "msg_types": ["/ibc.core.client.v1.MsgUpdateClient", "/ibc.core.channel.v1.MsgChannelOpenTry"], "tx_hash": "8BA9F6332E474C0836302AE254C1761D650D0DB72BAF10DB04EC0F728AC9ED37"}
2022-09-13T12:33:29.940563Z     info    Successful transaction  {"provider_type": "cosmos", "chain_id": "osmo-test-4", "gas_used": 258490, "fees": "", "fee_payer": "osmo177epemfjfz65j8u0dfy79953k8myw8fc648xa9", "height": 6636243, "msg_types": ["/ibc.core.client.v1.MsgUpdateClient", "/ibc.core.channel.v1.MsgChannelOpenTry"], "tx_hash": "4EBFA959BA28670406385D39628BD883707E99EBBDF71FB176C7E350749A0EE9"}
2022-09-13T12:33:54.984569Z     info    Successful transaction  {"provider_type": "cosmos", "chain_id": "osmo-test-4", "gas_used": 262037, "fees": "", "fee_payer": "osmo177epemfjfz65j8u0dfy79953k8myw8fc648xa9", "height": 6636248, "msg_types": ["/ibc.core.client.v1.MsgUpdateClient", "/ibc.core.channel.v1.MsgChannelOpenTry"], "tx_hash": "6325B48BA978103DE1061DF4B37C24991E915FA7FBE82DF137FEECA98104C79D"}
2022-09-13T12:34:20.470791Z     info    Successful transaction  {"provider_type": "cosmos", "chain_id": "osmo-test-4", "gas_used": 258160, "fees": "", "fee_payer": "osmo177epemfjfz65j8u0dfy79953k8myw8fc648xa9", "height": 6636253, "msg_types": ["/ibc.core.client.v1.MsgUpdateClient", "/ibc.core.channel.v1.MsgChannelOpenTry"], "tx_hash": "62301753D7FBDC6D4E2DC22C7CDD95C1FAC9091D81761E3ED99F2CBB2A0B8EFB"}
2022-09-13T12:34:45.410161Z     info    Successful transaction  {"provider_type": "cosmos", "chain_id": "osmo-test-4", "gas_used": 264371, "fees": "", "fee_payer": "osmo177epemfjfz65j8u0dfy79953k8myw8fc648xa9", "height": 6636258, "msg_types": ["/ibc.core.client.v1.MsgUpdateClient", "/ibc.core.channel.v1.MsgChannelOpenTry"], "tx_hash": "3840169E0A05211B1776C32789EAD1189625E4A0EC76A6908EBA467B87302FF5"}
2022-09-13T12:35:05.628756Z     error   Giving up on sending channel message after max retries  {"path_name": "juno-osmo-test", "chain_id": "osmo-test-4", "client_id": "07-tendermint-2571", "event_type": "channel_open_try", "max_retries": 5}
```

After this command the newly created path in the config file looks like this:
```
juno-osmo-test:
        src:
            chain-id: uni-3
            client-id: 07-tendermint-317
            connection-id: connection-278
        dst:
            chain-id: osmo-test-4
            client-id: 07-tendermint-2571
            connection-id: connection-2087
        src-channel-filter:
            rule: ""
            channel-list: []
```

Attempting to query for channels associated with the newly created connection yields no results:

```
osmosisd q ibc channel connections connection-2087 --node https://rpc-test.osmosis.zone:443
channels: []
height:
  revision_height: "6636330"
  revision_number: "4"
pagination:
  next_key: L3BvcnRzL3RyYW5zZmVyL2NoYW5uZWxzL2NoYW5uZWwtMTc2
  total: "0"
```

**Comment by jtieri** [comment] 2022-09-19 19:05
Upon trying to reproduce this issue today with @agouin we saw the channel handshake completing successfully on both mainnet and testnet between Juno & Cosmoshub.

The only issue noted during our testing was between Juno and Osmosis testnets where we saw logs around failed `MsgUpdateClient` on the Osmosis testnet with logs 
```
2022-09-19T18:14:14.010785Z     info    Error building or broadcasting transaction      {"provider_type": "cosmos", "chain_id": "osmo-test-4", "attempt": 1, "max_attempts": 5, "error": "rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: cannot update client with ID 07-tendermint-2571: failed to verify header: cant trust new val set: invalid commit -- insufficient voting power: got 651464, needed more than 700498: invalid request"}
```

I'm going to close this issue out for now but please feel free to reopen the issue or create a new one if you still observe this same behavior.

**Closed as completed by jtieri** 2022-09-19 19:05 UTC
