### ISSUE TITLE
ibc relayer betweet Gaiad and ethermint error

### ISSUE THREAD

**Issue by hoang14x** [cosmos/relayer#589] opened 2022-03-08 08:44 UTC
I have 2 chain Gaiad and ethermint

Connect chain 1 -> chain 2
``` rly tx link path1 -d -o 3s --home gaid1```

error
```I[2022-03-08|15:22:37.489] - [ibc-0] -> failed sending transaction:     
{"client_state":{"@type":"/ibc.lightclients.tendermint.v1.ClientState","chain_id":"astradev_9000-1","trust_level":{"numerator":"1","denominator":"3"},"trusting_period":"1540800s","unbonding_period":"1814400s","max_clock_drift":"600s","frozen_height":{"revision_number":"0","revision_height":"0"},"latest_height":{"revision_number":"0","revision_height":"0"},"proof_specs":[{"leaf_spec":{"hash":"SHA256","prehash_key":"NO_HASH","prehash_value":"SHA256","length":"VAR_PROTO","prefix":"AA=="},"inner_spec":{"child_order":[0,1],"child_size":33,"min_prefix_length":4,"max_prefix_length":12,"empty_child":null,"hash":"SHA256"},"max_depth":0,"min_depth":0},{"leaf_spec":{"hash":"SHA256","prehash_key":"NO_HASH","prehash_value":"SHA256","length":"VAR_PROTO","prefix":"AA=="},"inner_spec":{"child_order":[0,1],"child_size":32,"min_prefix_length":1,"max_prefix_length":1,"empty_child":null,"hash":"SHA256"},"max_depth":0,"min_depth":0}],"upgrade_path":["upgrade","upgradedIBCState"],"allow_update_after_expiry":true,"allow_update_after_misbehaviour":true},"consensus_state":{"@type":"/ibc.lightclients.tendermint.v1.ConsensusState","timestamp":"2022-03-08T08:21:49.614497Z","root":{"hash":"0bBpZAHuArdNh7pIO5f2Ch95gpZiOn4AfcyhJY4a7PU="},"next_validators_hash":"0664C811F21FA22330EE05C8C05CF178EE71C29F8DAB6763CB70CD897E504B49"},"signer":"cosmos1pkkayn066msg6kn33wnl5srhdt3tnu2vzasz9c"}
E[2022-03-08|15:22:37.490] - [ibc-0] -> err(rpc error: code = InvalidArgument desc = latest height revision number must match chain id revision number (0 != 1): invalid header height: invalid request) 
Error: error creating clients. Err: failed to create client on src chain{ibc-0}. Err: failed to send messages on chain{ibc-0}. Err: rpc error: code = InvalidArgument desc = latest height revision number must match chain id revision number (0 != 1): invalid header height: invalid request 
```

connect chain 2 -> chain 1
``` rly tx link path1 -d -o 3s --home gaid1```

error:
```
I[2022-03-08|15:38:25.431] - [astradev_9000-1] -> failed sending transaction: 
{"client_state":{"@type":"/ibc.lightclients.tendermint.v1.ClientState","chain_id":"ibc-0","trust_level":{"numerator":"1","denominator":"3"},"trusting_period":"1540800s","unbonding_period":"1814400s","max_clock_drift":"600s","frozen_height":{"revision_number":"0","revision_height":"0"},"latest_height":{"revision_number":"0","revision_height":"2854"},"proof_specs":[{"leaf_spec":{"hash":"SHA256","prehash_key":"NO_HASH","prehash_value":"SHA256","length":"VAR_PROTO","prefix":"AA=="},"inner_spec":{"child_order":[0,1],"child_size":33,"min_prefix_length":4,"max_prefix_length":12,"empty_child":null,"hash":"SHA256"},"max_depth":0,"min_depth":0},{"leaf_spec":{"hash":"SHA256","prehash_key":"NO_HASH","prehash_value":"SHA256","length":"VAR_PROTO","prefix":"AA=="},"inner_spec":{"child_order":[0,1],"child_size":32,"min_prefix_length":1,"max_prefix_length":1,"empty_child":null,"hash":"SHA256"},"max_depth":0,"min_depth":0}],"upgrade_path":["upgrade","upgradedIBCState"],"allow_update_after_expiry":true,"allow_update_after_misbehaviour":true},"consensus_state":{"@type":"/ibc.lightclients.tendermint.v1.ConsensusState","timestamp":"2022-03-08T08:37:40.047257499Z","root":{"hash":"G8N84judZ6UgQKjScWdxOGilpZDOO5Emiyn3T+CMKew="},"next_validators_hash":"1947C2F01A7868DCED4158B2E26FFA94E2A33614E9787CDC76CEF011F3F24D5E"},"signer":"ethm12x6rnfnavt8rd4sctsfgaz3wxt6sur4m6meey3"}
E[2022-03-08|15:38:25.431] - [astradev_9000-1] -> err(no concrete type registered for type URL /ethermint.types.v1.EthAccount against interface *types.AccountI) 
Error: error creating clients. Err: failed to create client on src chain{astradev_9000-1}. Err: failed to send messages on chain{astradev_9000-1}. Err: no concrete type registered for type URL /ethermint.types.v1.EthAccount against interface *types.AccountI 
```

**Comment by jtieri** [comment] 2022-04-29 17:30
I believe this is fixed now. @boojamya can you confirm that you did create a client for Evmos with the relayer and if so let's close out this issue?

**Comment by boojamya** [comment] 2022-04-29 17:37
Confirmed. `07-tendermint-742` was created on the hub connecting evmos using the relayer.

Hash: 6422F6A9A43CCDE701001F112D7098003351492A5EDE34B0FB9047949BA98965

Closing.

**Closed as completed by boojamya** 2022-04-29 17:37 UTC
Labels: T: Enhancement, C: Relayer

**Comment by parveenkaushikmajra** [comment] 2024-03-26 13:02
@boojamya i am getting the same error for two chains one is osmosis and other is evmos
Error is 
"Error: error creating clients: failed to create client on src chain{evmos_9000-1}: failed to find a matching client for the new client state: no concrete type registered for type URL /ibc.lightclients.localhost.v2.ClientState against interface *exported.ClientState"

**Comment by jtieri** [comment] 2024-03-29 17:48
> @boojamya i am getting the same error for two chains one is osmosis and other is evmos Error is "Error: error creating clients: failed to create client on src chain{evmos_9000-1}: failed to find a matching client for the new client state: no concrete type registered for type URL /ibc.lightclients.localhost.v2.ClientState against interface *exported.ClientState"

hey @parveenkaushikmajra the error message you shared seems to be related to the IBC localhost client actually and not Eth accounts like in the original post here. 

do you want to open a new issue and we can carry on this conversation over there?
