### ISSUE TITLE
undefined: secp256k1.VerifySignature

### ISSUE THREAD

**Issue by maxbry** [cosmos/relayer#1165] opened 2023-04-07 17:51 UTC
Steps to reproduce:
- freshly installed VM with Ubuntu 22.04 and Go 1.20.3
- `git clone https://github.com/cosmos/relayer.git`
- `cd relayer && git checkout v2.3.0`
- `make install`

Output:
```
installing rly binary...
# github.com/cosmos/relayer/v2/relayer/codecs/injective
relayer/codecs/injective/ethsecp256k1.go:201:19: undefined: secp256k1.VerifySignature
make: *** [Makefile:46: install] Error 1
```

**Comment by agouin** [comment] 2023-04-10 21:03
Are you maybe missing `gcc`?

```
docker run -it --rm --entrypoint bash ubuntu:22.04

apt update; apt install -y wget git make gcc

rm -rf /usr/local/go && wget https://go.dev/dl/go1.20.3.linux-amd64.tar.gz -O - | tar -C /usr/local -xz
export PATH=$PATH:/usr/local/go/bin

git clone --single-branch --branch v2.3.0 https://github.com/cosmos/relayer.git
cd relayer
make install

# builds successfully
```

**Comment by jasbanza** [comment] 2023-11-27 15:35
Confirmed that this is the problem. fresh ubuntu instance forgetting to update.

**Comment by jtieri** [comment] 2024-02-01 20:07
Closing this issue since @agouin's previous suggestion worked.

**Closed as completed by jtieri** 2024-02-01 20:07 UTC
