### ISSUE TITLE
Error: failed to get trusted header, please ensure header at the height 7918852 has not been pruned

### ISSUE THREAD

**Issue by virtualrobotix** [cosmos/relayer#1012] opened 2022-10-07 09:02 UTC
Hi guys,
 i properly configure the node and try to do a transfer between two network . So i did the same test on other node as cosmos and terra and all work fine .. now i try to open this channel 72 between terra and osmosis but optain this kind of issue . I try to transfer old ibc token so i think that i need no pruned node . I don't know if i understand correctly the problem .. do you have some node that can support this kind of transfer ?  Not pruned node on terra and osmosis , what is the number in the error ? The number of block ? on what node ? Is a node on terra or on osmosis for understand better what pruned node not supported by this transfer.
Thanks for support.

./rly tx transfer osmosis terra 100channel-72/uluna terra1dfejlf7xkxdjnhl52g9a630vssxka2fhdkpk2h channel-72 --path osmo-terra

Error: failed to get trusted header, please ensure header at the height 7918852 has not been pruned by the connected node: light block not found

root@vmi1016551:~/go/bin#

**Comment by jtieri** [comment] 2022-10-17 22:01
Hello there @virtualrobotix, sorry for the delay in response on this one somehow it slipped through the cracks.

Can you share your config along with what version of the relayer you are running? The relayer version can be retrieved by running `rly version`.

The number in your error message is indicating which block height the underlying node was attempting to query when it encountered the error. The node that the relayer is utilizing should be configured in your `config.yaml` file for the relayer.

It seems likely at a first glance that whichever node was being used does not contain the state at block height `7918852` and yes this could be caused by the pruning settings for that particular node as you mentioned.

**Comment by jtieri** [comment] 2022-10-26 18:09
@virtualrobotix I'm going to close this issue for now, if it's still relevant feel free to open it back up!

**Closed as completed by jtieri** 2022-10-26 18:09 UTC
