### ISSUE TITLE
Strange relayer behaviour cause clients to die

### ISSUE THREAD

**Issue by JokerTheBond** [cosmos/relayer#235] opened 2020-05-08 20:35 UTC
Hi I want to report a strange behaviour that I noticed in my relayer this morning.
I'll start with saying that I was using a very simple and defensive approach in order to update my client: an update every 5 minutes with the command rly tx raw update-client.
The time of the following logs is UTC +2. Every log is a couple where: the first log is the result of the update-client command on my chain (jtbchain) while the second log is the result of the command on gameofzoneshub.
Until this morning every log looked something like this:
```
Fri May  8 12:32:01 2020: Script is executing

Fri May  8 12:32:55 2020: {"height":"69976","txhash":"30015FC52EA53C97C0021BBA4CFCC42B0C7D3C032CA17624E882AED702690696","logs":[{"msg_index":0,"log":"","events":[{"type":"message","attributes":[{"key":"action","value":"update_client"}]}]}],"gas_wanted":"200000","gas_used":"135974"}

Fri May  8 12:33:11 2020: broadcast_tx_commit: Post failed: Post "http://35.233.155.199:26657": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
Both clients were being updated and everything was fine.
Then at a certain point I had a different log:
```
Fri May  8 12:37:01 2020: Script is executing

Fri May  8 12:41:09 2020: {"height":"70074","txhash":"0618EA509D5C9E131C7D3583AD9BE56BE91DE7CDF8992A52777279E3138463D8","logs":[{"msg_index":0,"log":"","events":[{"type":"message","attributes":[{"key":"action","value":"update_client"}]}]}],"gas_wanted":"200000","gas_used":"135974"}

Fri May  8 12:41:19 2020: ABCIQuery: Post failed: Post "http://35.233.155.199:26657": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
Please notice that now the ouput of the second log is "ABCIQuery", not more broadcast_tx_commit. Also, the first command took 4 minutes to execute which was alreeady strange...
After this happened, the relayer didn't worked as before.
The following log was this:
```
Fri May  8 12:42:01 2020: Script is executing

Fri May  8 12:43:21 2020: {"height":"0","txhash":"66B7A6E31760A4A957CAEB343AF48A1DEED1AC4B862A0381C272E01C4ABB1E2A","codespace":"client","code":9,"gas_wanted":"200000","gas_used":"66184"}

Fri May  8 12:43:31 2020: ABCIQuery: Post failed: Post "http://35.233.155.199:26657": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
I never had any error while updating my chain, and now I was getting code 9.
Next log:
```
Fri May  8 12:47:02 2020: Script is executing

Fri May  8 12:52:53 2020: All attempts fail:
#1: can't open lite client database: resource temporarily unavailable
#2: can't open lite client database: resource temporarily unavailable
#3: can't open lite client database: resource temporarily unavailable
#4: can't open lite client database: resource temporarily unavailable
#5: can't open lite client database: resource temporarily unavailable
#6: can't open lite client database: resource temporarily unavailable
#7: can't open lite client database: resource temporarily unavailable
#8: can't open lite client database: resource temporarily unavailable
#9: can't open lite client database: resource temporarily unavailable
#10: can't open lite client database: resource temporarily unavailable

Fri May  8 12:53:03 2020: ABCIQuery: Post failed: Post "http://35.233.155.199:26657": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
Seems like there was some kind of problem accessing the lite client of my chain.
And then error like this went on for about three hours and so my connection died. If needed I can send the full log file and the script that I'm using to update the clients.

**Comment by jackzampolin** [comment] 2020-05-11 21:58
This issue was likely caused by congestion on the hub RPC endpoint. The `broadcast_tx_commit` failure just leaves the transaction in the mempool so it would make sense that these txs were eventually included in blocks. The `ABCIQuery: Post failed` indicates a failed query to get headers for the local lite client. This was likely caused by RPC congestion. The local database contention issue is likely due to retries for the failed header call locking up the database and subsequent calls running into the same contention. I'm going to close this issue as non-actionable, but this is an excellent writeup @JokerTheBond !

**Closed as completed** 2020-10-16 18:36 UTC
