### ISSUE TITLE
rly pth show output incorrect due to IBC proto migration

### ISSUE THREAD

**Issue by asmodat** [cosmos/relayer#238] opened 2020-05-11 18:20 UTC
How to reproduce (rly version v0.5.0)

1. Establish Connection
```
m="put some random mnemonic here" && \
 j1=./config-1.json && \
 j2=./config-2.json && \
 k=your_key_prefix && \
 i=$(cat $j1) && s=$(echo $i | jq -r '."chain-id"') && \
 o=$(cat $j2) && d=$(echo $o | jq -r '."chain-id"') && \
 p="$s_$d" && \
 rly ch d $s && rly ch d $d && \
 rly ch a -f $j1 && rly ch a -f $j2 && \
 rly k d $s $k$s ||: && rly k d $d $k$d ||: && \
 rly k r $s $k$s "$m" && rly k r $d $k$d "$m" && \
 rly ch e $s key $k$s && rly ch e $d key $k$d && \
 rly l d $s && rly l d $d && rly pth d $p || : && \
 rly pth gen $s transfer $d transfer $p -f && \
 rly l i $s -f && rly l i $d -f && \
 rly l u $s && rly l u $d && \
 rly tst req $s || : && rly tst req $d || : && \
 rly q bal $s -j && rly q bal $d -j && \
 rly tx clnts $p -d &> clnts.log; wait && \
 rly tx conn $p -d &> conn.log; wait && \
 rly tx chan $p -d &> chan.log; wait && \
 rly pth s
```

2. Reproduce Problem
```
rly tx clnts $p -d
rly tx conn $p -d
rly tx chan $p -d
```

Expected any output whatsoever, and we get nothing despite --debug flag

The output of the first command sequence stores const,conn and chan in log files, those log files indicate successful connection while status claims there is no connection and no channel created

```
  SRC(kira-alpha)
    ClientID:     wtjgdppqgm
    ConnectionID: nohuwvfjww
    ChannelID:    zvdrhutltn
    PortID:       transfer
  DST(kira-1-2)
    ClientID:     ylmhjtfqan
    ConnectionID: gszgbfoiyg
    ChannelID:    vryzlorioy
    PortID:       transfer
  STATUS:
    Chains:       ✔
    Clients:      ✔
    Connection:   ✘
    Channel:      ✘
```

I do not understand why despite  Connection:   ✘ and Channel:      ✘, trying to rly tx conn $p -d && rly tx chan $p -d would result in no output or error indication whatsoever.

Also, those commands should not be passing if the connection or channel was not established

**Comment by asmodat** [comment] 2020-05-11 18:24
If there is no Connection or Channel creation then rly tx should not be responding with exit code 0. That is incorrect behavior

What's worse it spits success in the first run - including standard output despite status showing something totally different after those commands are executed

If you retry - even with debug it spits nothing to std err and out, just passes with code 0

**Comment by jackzampolin** [comment] 2020-05-11 21:05
@asmodat Thank you for the bug report. A couple of items here:

1. If you would like to test IBC this repo contains a number of scripts for spinning up chains locally in a number of different configurations as well as config that is ready to go. I've just [opened an issue](https://github.com/iqlusioninc/relayer/issues/239) to document them and their usage better. When submitting issues, please reproduce using these scripts. The script you have above ☝️ amounts to `./scripts/two-chainz local skip && ./scripts/config-relayer skip`. 
1. `Expected any output whatsoever, and we get nothing despite --debug flag`. I'm unable to reproduce this. Here is the output from those commands [with and without debug logging](https://gist.github.com/jackzampolin/e30fc0f111f53f429060d4a0a9ed773b). You can clearly see the difference above.
1. I do see that `rly pth show` has an issue here and is improperly showing status for the channel and connection. Thank you for reporting this issue. This is related to the recent update to proto and the open indicator appears to have changed from `OPEN` to `"state": 3`:
```
$ rly pth show demo
Path "demo" strategy(naive):
  SRC(ibc0)
    ClientID:     ibconeclient
    ConnectionID: ibconeconnection
    ChannelID:    ibconexfer
    PortID:       transfer
  DST(ibc1)
    ClientID:     ibczeroclient
    ConnectionID: ibczeroconnection
    ChannelID:    ibczeroxfer
    PortID:       transfer
  STATUS:
    Chains:       ✔
    Clients:      ✔
    Connection:   ✘
    Channel:      ✘
```
1. You can tell that this is the channels and connections have been created correctly by the txs and by querying them directly:
```
relayer [master] :> rly q chan ibc0 ibconexfer transfer
{"channel":{"id":"ibconexfer","port_id":"transfer","state":3,"ordering":2,"counterparty":{"port_id":"transfer","channel_id":"ibczeroxfer"},"connection_hops":["ibconeconnection"],"version":"ics20-1"},"proof":{"proof":{"ops":[{"type":"iavl:v","key":"Y2hhbm5lbEVuZHMvcG9ydHMvdHJhbnNmZXIvY2hhbm5lbHMvaWJjb25leGZlcg==","data":"1wEK1AEKKAgIEAoYIyog4XDFd05ndJCTePJX+WWtvJzWxXrNc0OEaDunfox6sv0KKAgEEAMYIyog5GxPr2mYZy32eIhhqp025to1OjNwTS5DTZFNaFrecpQKKAgCEAIYIyogbxSKG+Z84enaJMAZIJ0UFuexY7+/OcbxSymPDRn34nEaVAouY2hhbm5lbEVuZHMvcG9ydHMvdHJhbnNmZXIvY2hhbm5lbHMvaWJjb25leGZlchIgMhsMeYKYhPlMLQmXJhm0I5Uirpqbs7wjgbWwix5FKbIYIw=="},{"type":"multistore","key":"aWJj","data":"CuoEChAKB3VwZ3JhZGUSBQoDCJoCCi8KBG1pbnQSJwolCJoCEiBjKWBlD5+GFkZ3e6jCsmA27lEGX/Q5LMb/+3z+8Cchzgo1CgpjYXBhYmlsaXR5EicKJQiaAhIgJWykyCwCUVoQAW4lI5vOUCyRjKLSYtFv/wacJWJ2JVYKMwoIc2xhc2hpbmcSJwolCJoCEiA16ZSAQDPOPFT09x/E6vc+09tg5Izu2ZZngjGfK+hoiwoyCgdzdGFraW5nEicKJQiaAhIgEMfnaz0BQ8Uq4izzcGoP+j7q1LRSCrbG3ywwdqKDpusKLwoEYmFuaxInCiUImgISIOYGIT9YsdXnP1T+ntkOCYvjhNKHAbizmiauMr26exWUChAKDm1lbV9jYXBhYmlsaXR5CjMKCHRyYW5zZmVyEicKJQiaAhIgrXcSzKUSdAKJtxSxG5jzxEvR/ybpMTSdLekqEB/ikQcKLgoDaWJjEicKJQiaAhIg0+AURyR7pcfjCe1wLMT/V27ilcHFm3uBrLxA8yMwDwUKLgoDZ292EicKJQiaAhIgYM0TfBli7KxhY4nWgDSDPykhUJwtKFql9RU5l86WinQKLgoDYWNjEicKJQiaAhIgDJw3KWqgYih6tBb8KILOrXgbqzdrDIaE5M6pxjswU/IKEQoIZXZpZGVuY2USBQoDCJoCCjcKDGRpc3RyaWJ1dGlvbhInCiUImgISIPDTp/2vF3FGRqq7BQK8DQco8TfSzpUQqRlA3xjUaqUuCjEKBnBhcmFtcxInCiUImgISIAUe+8MBTY6kDzlo6eATu9SdelUIqDbVjx96BsDutNQ9"}]}},"proof_path":{"key_path":{"keys":[{},{},{},{},{}]}},"proof_height":"282"}
relayer [master] :> rly q conn ibc0 ibconeconnection
{"connection":{"id":"ibconeconnection","client_id":"ibconeclient","versions":["1.0.0"],"state":3,"counterparty":{"client_id":"ibczeroclient","connection_id":"ibczeroconnection","prefix":{"key_prefix":"aWJj"}}},"proof":{"proof":{"ops":[{"type":"iavl:v","key":"Y29ubmVjdGlvbnMvaWJjb25lY29ubmVjdGlvbg==","data":"7wEK7AEKKAgIEAoYIyIgTrA+r8a6pcnS4zO3xSoVMRY+FAqMUb2rVJyikOOeNhMKKAgGEAcYIyIgAUOs6RKKkfL+/0Cw/Grds1+hxuLGHiK6nOW69IWVNugKKAgEEAQYHiogDFsQXfHjlXYvesUMlh47rPe+lMqP8DRGwJ9++KszdOUKKAgCEAIYHiIgCGNkmhwFG1+BQlxag9Fvx9EPygIe7jTIIWBb+w+61EgaQgocY29ubmVjdGlvbnMvaWJjb25lY29ubmVjdGlvbhIgI2TKgWzq3UqR5eFhA/1dNo5PYxdBZbf+03pCOrLSQi0YFw=="},{"type":"multistore","key":"aWJj","data":"CuoECjIKB3N0YWtpbmcSJwolCMECEiDutbNZ297ikDSGlz0Ry9UtkmxwfZvTyKMadb5EBnkUiAovCgRiYW5rEicKJQjBAhIgd6RMtURUzKWcrIZLAyc00mO/gcju1xfwEiKkjsu/itQKEAoObWVtX2NhcGFiaWxpdHkKMwoIdHJhbnNmZXISJwolCMECEiCtdxLMpRJ0Aom3FLEbmPPES9H/JukxNJ0t6SoQH+KRBwouCgNnb3YSJwolCMECEiBgzRN8GWLsrGFjidaANIM/KSFQnC0oWqX1FTmXzpaKdAouCgNhY2MSJwolCMECEiAMnDcpaqBiKHq0Fvwogs6teBurN2sMhoTkzqnGOzBT8goRCghldmlkZW5jZRIFCgMIwQIKNwoMZGlzdHJpYnV0aW9uEicKJQjBAhIggDF7F44xFMo+wYyUq1MjOIkc6fZZ7vnpmw+Lre4+td8KMQoGcGFyYW1zEicKJQjBAhIgBR77wwFNjqQPOWjp4BO71J16VQioNtWPH3oGwO601D0KLgoDaWJjEicKJQjBAhIg0+AURyR7pcfjCe1wLMT/V27ilcHFm3uBrLxA8yMwDwUKEAoHdXBncmFkZRIFCgMIwQIKLwoEbWludBInCiUIwQISIDv3N9KjTzFunEsXtSVdtpVTq2k+TJY7MRwJcwOPDi5/CjUKCmNhcGFiaWxpdHkSJwolCMECEiAlbKTILAJRWhABbiUjm85QLJGMotJi0W//BpwlYnYlVgozCghzbGFzaGluZxInCiUIwQISIC3E1ffW31SX30KiDHGyAnsc1StF+0SHRmm3IlJNQiji"}]}},"proof_path":{"key_path":{"keys":[{},{}]}},"proof_height":"321"}
```
1. I'm fairly sure that if the commands end with improperly created channels they output `exit 1`. Please share repro case if I'm wrong. Also `If you retry - even with debug it spits nothing to std err and out, just passes with code 0` this is because the channels are properly created

**Comment by asmodat** [comment] 2020-05-11 21:21
Via the PM all was explained to me precisely, the bug is actually with the Status query, not the tx, the node is actually connected.

The bug is that --debug using any of those:
```
rly tx clnts $p -d
rly tx conn $p -d
rly tx chan $p -d
```
should output "already connected" or something of the sort if they are retried, otherwise status not connected + no output from those commands above after re-try to establish the connection is confusing

**Comment by jackzampolin** [comment] 2020-05-11 21:28
closed by above commit

**Closed as completed by jackzampolin** 2020-05-11 21:28 UTC
Labels: T: Bug 🪲
